Numpy stands for numerical python

In [2]:
import numpy as np

# Creating arrays

In [ ]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array((1, 2, 3, 4, 5))

# The np.array() function is designed to accept any array-like object including lists, tuples, and even other arrays

print(arr_1)
print(arr_2)

print(type(arr_1))
print(type(arr_2))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
# Dimension of array

arr= np.array(42)      # 0 dimension 
arr = np.array([1, 2, 3, 4, 5])    # 1D array
arr = np.array([[1, 2, 3], [4, 5, 6]])    # 2D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])      # 3D array

In [10]:
# Creating array with specific number of dimensions and verifying the dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array Indexing

In [ ]:
# 1D array

arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[2] + arr[3])

1
7


In [12]:
# 2D array

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


# Array slicing

In [16]:
# 1D array

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[-3:-1])
print(arr[1:5:2])

[2 3 4 5]
[5 6]
[2 4]


In [19]:
# 2D array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# Array copy and view

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

x = arr.view()
arr[0] = 42

print(arr)
print(x)

None
[1 2 3 4 5]


# Array shape and reshape

In [24]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Joinnig arrays

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [29]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting arrays

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [39]:
# 2D array

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [42]:
newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Array search, sort and filter

In [43]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


searchsorted() : ( Used on sorted array ) It performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order

In [47]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

x = np.searchsorted(arr, 7, side='right')

print(x)

1
2


In [48]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [50]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# It returns a copy of the array, leaving the original array unchanged

[0 1 2 3]


In [ ]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [53]:
# Creating a filter array

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
